apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: main-api-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: douglasg96/kantox-main-api:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
              name: main-api-config
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          